language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
  - julia: nightly
after_success:
  - julia -e 'cd(Pkg.dir("MMTF")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'